### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by buep** [Praqma/praqma-CENTOS-MultiTool#2]
Note that our repos that only is used for docker images starts with 'docker', e.g. https://github.com/Praqma/docker-gh-pages which becomes gh-pages docker image on our docker hub. I hope you can still rename it...

**Comment by KamranAzeem** [comment]
Done! Thanks!

**Comment by buep** [comment]
yep, according to our internal discussions we keep the name for now because Docker don't like us to use docker-word.
